---

- hosts: rayworkernodes
  vars:
   user: "{{ lookup('env','USER') }}"
  tasks:
  - name: STOP ray worker
    delegate_to: 127.0.0.1
    ansible.builtin.command: ssh {{inventory_hostname}} 'source {{rayvenvpath}}/bin/activate && ray stop'
    register: result



- hosts: rayheadnodes
  vars:
   user: "{{ lookup('env','USER') }}"
  tasks:
  - name: STOP ray head
    delegate_to: 127.0.0.1
    ansible.builtin.command: ssh {{inventory_hostname}} 'source {{rayvenvpath}}/bin/activate && ray stop'
    register: result

...